import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { NextAuthOptions } from "@/config";
import Header from "./src/components/ui/Header";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
