import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/ui/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function UserLayout({ children }) {



    return (

        <div>
            <div><Header /></div>
            <div>{children}</div>

        </div>
    );
}
